# Generated by Django 3.1.1 on 2020-09-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newclass1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('phone_num', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='newclass',
            name='new_num',
            field=models.IntegerField(default=0),
        ),
    ]
